export const TABLES = {
    CHEMICAL_UNIT: 'CHEMICAL_UNIT',
    CHEMICAL_ATOM: 'CHEMICAL_ATOM',
    CHEMICAL_AGGREGATE: 'CHEMICAL_AGGREGATE',
    CHEMICAL_AGGREGATE__CHEMICAL_ATOM: 'CHEMICAL_AGGREGATE__CHEMICAL_ATOM',
    CHEMICAL_COMPLEX__CHEMICAL_AGGREGATE: 'CHEMICAL_COMPLEX__CHEMICAL_AGGREGATE',
    CHEMICAL_COMPLEX: 'CHEMICAL_COMPLEX',

    ROLE: 'ROLE',
    USER: 'USER',
    TOKEN: 'TOKEN',
}