export const TABLES = {
    CHEMICAL_UNIT: 'CHEMICAL_UNIT',
    CHEMICAL_ATOM: 'CHEMICAL_ATOM',
    CHEMICAL_AGGREGATE: 'CHEMICAL_AGGREGATE',

    ROLE: 'ROLE',
    USER: 'USER',
    TOKEN: 'TOKEN',
}