export const TABLES = {
    CHEMICAL_UNIT: 'CHEMICAL_UNIT',
    CHEMICAL_COMPLEX_TEXT: 'CHEMICAL_COMPLEX_TEXT',

    CHEMICAL_ATOM: 'CHEMICAL_ATOM',
    CHEMICAL_AGGREGATE: 'CHEMICAL_AGGREGATE',
    CHEMICAL_AGGREGATE__CHEMICAL_ATOM: 'CHEMICAL_AGGREGATE__CHEMICAL_ATOM',
    CHEMICAL_COMPLEX__CHEMICAL_AGGREGATE: 'CHEMICAL_COMPLEX__CHEMICAL_AGGREGATE',
    CHEMICAL_COMPLEX: 'CHEMICAL_COMPLEX',


    FERTILIZER: 'FERTILIZER',
    INGREDIENT: 'INGREDIENT',

    ROLE: 'ROLE',
    USER: 'USER',
    TOKEN: 'TOKEN',
}